# Site settings
author: Kevin Britt
title: No End in Sight
header-img: img/home-bg.png
email: kbritt510@gmail.com
copyright_name: Kevin Britt
description: > # this means to ignore newlines until "baseurl:"
  The Journey of Changing Careers Amidst a Pandemic
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Rollo510

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
